---
version: 3

images:
  base_image:
    name: registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:6c79f4fb38a20d496c859025d57e4074835e849d5d14819c4e021ad78446bce8

dependencies:
  ansible_core:
    package_pip: ansible-core==2.21.2
  ansible_runner:
    package_pip: ansible-runner==2.4.3
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  python: requirements.txt
  system: |
    git-core [platform:rpm]
    sshpass [platform:rpm]
    rsync [platform:rpm]
    gzip [platform:rpm]
    tar [platform:rpm]
    openssh [platform:rpm]

options:
  package_manager_path: /usr/bin/microdnf
