---
version: 3

images:
  base_image:
    name: registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:e1c4703364c5cb58f5462575dc90345bcd934ddc45e6c32f9c162f2b5617681c

dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.5
  ansible_runner:
    package_pip: ansible-runner==2.4.1
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  python: requirements.txt
  system: |
    git-core [platform:rpm]
    sshpass [platform:rpm]
    rsync [platform:rpm]
    gzip [platform:rpm]
    tar [platform:rpm]
    openssh [platform:rpm]

options:
  package_manager_path: /usr/bin/microdnf
