---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:fc9101f71f5b1430fba250392cd7d4db5842eb3cc9317dea013a5345c03624ac
dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.2
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
