---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:07644d4a6f3ef6fe5ffa533b85e8b6c95ea8eca176c7592b2f9b31ca4fc4fbf3
dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.4
  ansible_runner:
    package_pip: ansible-runner==2.4.1
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
