---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:88751cd45b1ca5a72cbdaf8b90bbda274bb367972ae86116b9382ab7ad7e2137
dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.5
  ansible_runner:
    package_pip: ansible-runner==2.4.1
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
