---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:142a573b3f6fa84946509723e4e1c81fe3805048132133e9d141ff2c0222e510
dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.3
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
