---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:494a21c8ca29252a4436e41fb3761609e2f6ac0aecd09d113b4fcfdedf193923
dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.4
  ansible_runner:
    package_pip: ansible-runner==2.4.1
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
