---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:0332eeb216229a949b591ccbd54644cd2145d5748c4a31bb66119d17f9ba4494
dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.5
  ansible_runner:
    package_pip: ansible-runner==2.4.1
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
