---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:3acd23b5ef721799f0d9566777995451757bd3ffb5ac80920eedb6bec831e1e5
dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.5
  ansible_runner:
    package_pip: ansible-runner==2.4.1
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
