---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:9a1c01eeece085e7b2a9d8edc7d107afccb27f9997ba97802eee701528b09e6b
dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.2
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
