---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:801c7bc44d14a3c5c282651cfa6ad455f4504e645f60b14c8b7eeaedbe8e7b89
dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.3
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
