---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:665b76306a4ba4f947c56a7c9c961d26910ddeafd2bf7493aa932c0410d15047
dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.4
  ansible_runner:
    package_pip: ansible-runner==2.4.1
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
