---
collections:
  - name: ansible.netcommon
    version: 8.0.0
  - name: ansible.posix
    version: 2.0.0
  - name: community.general
    version: 8.3.0
  - name: freeipa.ansible_freeipa
    version: 1.14.7
  - name: hetzner.hcloud
    version: 4.3.0
  - name: containers.podman
    version: 1.16.4
roles:
  - name: geerlingguy.ntp
