---
collections:
  - name: ansible.netcommon
    version: 7.1.0
  - name: ansible.posix
    version: 2.0.0
  - name: community.general
    version: 8.3.0
  - name: freeipa.ansible_freeipa
    version: 1.14.4
  - name: hetzner.hcloud
    version: 4.2.2
  - name: containers.podman
    version: 1.16.3
roles:
  - name: geerlingguy.ntp
