---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:49a66054787d55e19bf58a63416b39521bca9a53cb63d347d48149479ae7749a
dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.2
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf