---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:dca5d1e1fc5c2974ed4b99911a2bde2474e00de1230bce211dacab8613859028
dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.6
  ansible_runner:
    package_pip: ansible-runner==2.4.1
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf