---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:6ae35e4f4d49b076246e4c8a97f056bac3dca2798ffb159daa399ebab0e5f754
dependencies:
  ansible_core:
    package_pip: ansible-core==2.21.3
  ansible_runner:
    package_pip: ansible-runner==2.4.3
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf