---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:3f9cdb100f3269827001d12b2030685ec4b7d1e0551c9657e8875327e65f9d5b
dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.6
  ansible_runner:
    package_pip: ansible-runner==2.4.1
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf