---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:483681ad1f2a982d2bbfe70c6599269d1b429276dec4b66b921fbba606f3b627
dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.5
  ansible_runner:
    package_pip: ansible-runner==2.4.1
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf