---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:ab1861c3914d53967d379a0ebe1960240e1ff89a5256678655fd92263f4f2567
dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.6
  ansible_runner:
    package_pip: ansible-runner==2.4.1
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf