---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:590cf0364b30e5903229904d2a80cc21b7641c90366d3e231ce84be1efdaa16d
dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.3
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf