---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:537fa06315506f9c05d8e527b17069ef21583091ad375d500a414ad31eaa8f65
dependencies:
  ansible_core:
    package_pip: ansible-core==2.21.0
  ansible_runner:
    package_pip: ansible-runner==2.4.3
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf