---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:5300105834d8a87c42ed3c8aa785e4d3a38dbb0e45280de1543f19d00464f88b
dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.6
  ansible_runner:
    package_pip: ansible-runner==2.4.1
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf