---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:b3b4913725f229b300d76d2737bcdb021a89c1c49d2adfd6e0507151ef3dd4a2
dependencies:
  ansible_core:
    package_pip: ansible-core==2.21.2
  ansible_runner:
    package_pip: ansible-runner==2.4.3
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf