---
collections:
  - name: kubernetes.core
    version: 5.3.0
  - name: redhat_cop.controller_configuration
    version: 2.3.1
  - name: ansible.posix
    version: 2.0.0
  - name: community.okd
    version: 4.0.2
  - name: redhat_cop.ah_configuration
    version: 1.1.1
  - name: redhat_cop.ee_utilities
    version: 2.0.7
  - name: redhat_cop.aap_utilities
    version: 2.2.4
  - name: operator_sdk.util
    version: "0.5.0"
